### ISSUE TITLE
Question about popularity, and transactions (separate questions)

### ISSUE THREAD

**Issue by kswope** [go-testfixtures/testfixtures#23]
Coming from the rails world I'm just baffled as to why this, the most popular golang database fixture package, only has 151 stars.  Do gophers not test with databases?  Is everybody just mocking database queries (which is insane)?  Do they just not test?

Does it make sense to have the option of passing a sql.Tx so tests can be run in parallel?  (and disable the automatic database cleaning - which, by the way, is greatly appreciated)

**Comment by andreynering** [comment]
Hi @kswope! Thanks for opening this issue.

I haven't done much marketing if this lib after the initial versions, this explains why I don't have a lot of stars. Development has being also a bit slow recently. (I would be a lot happier if I had more help with it).

There's a lot of discussion out there about how to test database driven apps. Some Gophers user interface and mocks, others test with a database but use an ad hoc solution instead of this lib. There's no single answer for this.

About your feature request, I just opened #24 and will close this one. But feel free to comment if you still have doubts.

**Comment by kswope** [comment]
I don't think you have to do a lot of marketing if you are in second place of a google search for "golang fixtures",  I'm beginning to suspect that gophers don't do a lot of live database testing, probably mocking as you said.  In my opinion the rails world has gained a lot of experience and wisdom on subjects like this.
