### ISSUE TITLE
Cannot change time.Location of parsing date

### ISSUE THREAD

**Issue by bbq-all-stars** [go-testfixtures/testfixtures#37]
I would like to change time.Location of date, but cannot change because of this code.

https://github.com/go-testfixtures/testfixtures/blob/fa3fb89109b0b31957a5430cef3e93e535de362b/time.go#L25-L34

So, I fixed my yaml file the following temporary.

```
-  datetime: 2018-01-01 18:00:00
+  datetime: RAW="2018-01-01 18:00:00"
```

Is there other solution?

**Comment by andreynering** [comment]
Hi @bbq-all-stars!

Indeed, I misses this use case.

It's probably possible to allow that by editing [the time layout this](https://github.com/go-testfixtures/testfixtures/blob/fa3fb89109b0b31957a5430cef3e93e535de362b/time.go#L8).

The [Go time documentation](https://golang.org/pkg/time/) tells available layout for setting time zones like:

- `MST`
- `-0700`
- `-07:00`
- `-07`
- `Z0700`
- `Z07:00`
- `Z07`

I would be happy to review a PR for it.

**Comment by gmassman** [comment]
@andreynering I'm running into this issue as well. All my yaml dates look like `2019-02-25 08:00:00`, but are then inserted as `2019-02-25 08:00:00 -0800 PST`. I'd like to work on fixing the issue, but I'm not quite sure how to work around the `time.Local` in line 27. Do you have any suggestions on how to proceed?

For context, I ran into this issue when running tests with GH Actions. Not sure if there's a way to ensure local time is always UTC, that seems like the simplest workaround. Otherwise I'll have to go with the RAW= solution proposed above.

**Comment by andreynering** [comment]
Hi @gmassman,

> Not sure if there's a way to ensure local time is always UTC

Well, you could run the following line as the first thing in your program or test:

```go
time.Local = time.UTC
```

Make sure that's what you really want to do, though. And of course, that affects everything and not just testfixtures.

---

Sorry for keeping this issues open for so long, I really forgot about it. I added it to my TODO list to not forget about.

In the meantime you decide to try opening a PR with the [proposed solution](https://github.com/go-testfixtures/testfixtures/issues/37#issuecomment-425670661) yourself, I'll be happy to review it.

**Comment by gmassman** [comment]
@andreynering You're right, I don't want to modify `time.Local` in my tests. I've [created a PR](https://github.com/go-testfixtures/testfixtures/pull/55) with the proposed changes, please review when you've got a chance. Thanks!

**Comment by andreynering** [comment]
Hi @bbq-all-stars,

With [v3](https://github.com/go-testfixtures/testfixtures/releases/tag/v3.0.0) released testfixtures now both supports more formats and allows you to chose which time zone dates will be parsed.
