### ISSUE TITLE
Provide CLI to allow database seeding outside of tests

### ISSUE THREAD

**Issue by Jerome1337** [go-testfixtures/testfixtures#54]
It would be great to have a command line interface with basic fixtures load/unload commands.

This would allow users to seed database using same fixtures and use them in development environment. It would be useful for manual testing or as demonstration data.

**Comment by andreynering** [comment]
Hi @Jerome1337, thanks for opening this issue!

I thought about this in the past, but didn't know if it'd be really useful.

A couple of thoughts regarding the implementation:

- The Oracle driver is a pain to compile a binary with; you have to have the right dynamic libraries (OCI) available, and you can only connect to databases in the same version of the dynamic libraries (10, 11, etc). I plan to remove Oracle support in v3, so this CLI version can already ignore Oracle;
- I think it makes sense to ship this with v3;
- For SQLite, since it depends on C, it should protected with a `sqlite` build tag, so people can still compile for PostgreSQL/MySQL/SQLServer without a C compiler available. Released versions will include SQLite.

**Comment by Jerome1337** [comment]
@andreynering Do you need help (you may don't have time to create every features listed) to provide this feature into the v3.0 milestone?

**Comment by andreynering** [comment]
@Jerome1337 Help is always welcome. If you decide to try implementing this, feel free to ask for help if needed. Otherwise, I'll do it myself at some point.

I'd use the [github.com/spf13/pflag](http://github.com/spf13/pflag) as the flag library. We should likely allow environment variables for the connection strings, too.

**Comment by andreynering** [comment]
This is now complete (but not yet released) in the WIP [v3 branch](https://github.com/go-testfixtures/testfixtures/pull/57).

See [this file](https://github.com/go-testfixtures/testfixtures/pull/57/files#diff-de7490692e588ab7cfa014c8881b321c) to check the current state.

Feedback is welcome 🙂

**Comment by andreynering** [comment]
Oh, I forgot to add a flag to dump (instead of load) fixtures. I'll do that soon.

**Comment by andreynering** [comment]
This is now done as part of the v3 release: https://github.com/go-testfixtures/testfixtures/releases/tag/v3.0.0

**Comment by Jerome1337** [comment]
@andreynering It would be great to access this command (`testfixtures`) directly after we get the go package with `go get` command instead of downloading it from the GitHub release page. What do you think about that?

**Comment by andreynering** [comment]
@Jerome1337 Do you use GOPATH or Go Modules?

While that don't happen automatically (and there isn't much I can do about it), it relatively trivial to compile the command line yourself.

Using Go Modules:

```bash
git clone https://github.com/go-testfixtures/testfixtures
cd tesfixtures
go install [-tags sqlite] ./cmd/testfixtures
```

It'd be also easy for me to publish to Homebrew.

**Comment by jordantomax** [comment]
+1 for Homebrew
